package Galuga::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Galuga::Schema',
    
    
);

=head1 NAME

Galuga::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Galuga>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Galuga::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.43

=head1 AUTHOR

Yanick Champoux

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
